# Generated by Django 5.2 on 2025-04-10 08:47

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        email='admin@example.com',
        password='admin123'
    )

def delete_superuser(apps, schema_editor):
    User.objects.filter(username='admin').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
