# Generated by Django 5.2 on 2025-04-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0002_auto_20250410_1147"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChessMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_number", models.PositiveIntegerField()),
                ("from_square", models.CharField(max_length=2)),
                ("to_square", models.CharField(max_length=2)),
                ("piece", models.CharField(max_length=10)),
                (
                    "captured_piece",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="chess.chessgame",
                    ),
                ),
            ],
        ),
    ]
