# Generated by Django 5.2 on 2025-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0003_chessmove"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="move_history",
            field=models.TextField(default="[]"),
        ),
    ]
