# Generated by Django 5.2 on 2025-04-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0004_chessgame_move_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="chessgame",
            name="current_turn",
            field=models.CharField(default="white", max_length=5),
        ),
    ]
